# Generated by Django 3.2.9 on 2021-11-21 22:02

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20211119_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.IntegerField(primary_key=django.db.models.fields.AutoField, serialize=False),
        ),
    ]
