# Generated by Django 3.2.9 on 2021-11-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_ser_id'),
        ('customer', '0003_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='services_name',
            field=models.ManyToManyField(to='service.service'),
        ),
    ]
