# Generated by Django 3.2.9 on 2021-11-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ser_id',
            field=models.IntegerField(),
        ),
    ]
